yeniProje/Models/urun.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace yeniProje.Models
{
    public class urun
    {
        public int id { get; set; }
        public string urunismi { get; set; }
        public double fiyati { get; set; }
        public int adet { get; set; }
        public string aciklama { get; set; }

    }
}

yeniProje/Controllers/urunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using yeniProje.Models;
namespace yeniProje.Controllers
{
    public class urunController : Controller
    {
        // GET: urun
        public ActionResult Index()
        {
            return View();
        }
        urunCONTEXT db = new urunCONTEXT();
        public ActionResult urungir()
        {

            return View();
        }
        [HttpPost]
        public ActionResult urungir(urun yeniurun)
        {

            if (ModelState.IsValid == true)
            {
                db.urunler.Add(yeniurun);
                db.SaveChanges();
                ViewBag.mesaj = "Ürün kaydınız başarılı";
            }

            return View();
        }
        public ActionResult listele()
        {
            var veri = db.urunler.ToList();
            return View(veri);
        }
        public ActionResult zam()
        {

            return View();
        }
        [HttpPost]
        public ActionResult zam(double zamorani)
        {
            double artist = 1 + (zamorani / 100);
            var vericek = db.urunler.ToList();

            foreach (var item in vericek)
            {
                var zamlanacak = db.urunler.Find(item.id);
                zamlanacak.fiyati = zamlanacak.fiyati * artist;
                db.SaveChanges();
            }

            return RedirectToAction("listele");


        }
        public ActionResult indirimyap()
        {

            return View();
        }
        [HttpPost]
        public ActionResult indirimyap(double indirimorani, double indirimlimiti)
        {
            double azalis = 1 - (indirimorani / 100);
            var vericek = db.urunler.ToList();

            foreach (var item in vericek)
            {
                if (item.fiyati < indirimlimiti)
                {
                    var zamlanacak = db.urunler.Find(item.id);
                    zamlanacak.fiyati = zamlanacak.fiyati * azalis;
                    db.SaveChanges();

                }
                else
                {
                    return RedirectToAction("listele");
                }

            }
            return RedirectToAction("listele");
        }

        public ActionResult seçim(int? id)
        {
            urun yeniurun = new urun();
            if (id == null)
            {
                yeniurun = db.urunler.Take(1).FirstOrDefault();

            }
            if (id == 1)
            {
                double maxveri = db.urunler.Max(i => i.fiyati);
                yeniurun = (from c in db.urunler
                            where c.fiyati == maxveri
                            select c).FirstOrDefault();
            }
            else if (id == 2)
            {
                double minveri = db.urunler.Min(i => i.fiyati);
                yeniurun = (from a in db.urunler
                            where a.fiyati == minveri
                            select a).FirstOrDefault();

            }
            else if (id == 3)
            {
                int eyau = db.urunler.Max(i => i.adet);
                yeniurun = (from e in db.urunler
                            where e.adet == eyau
                            select e).FirstOrDefault();
            }
            return View(yeniurun);
        }
        public ActionResult azalt(int id)
        {
            urun yeniurun = new urun();
            var gelenidbilgisininkodunubulmaseysi = db.urunler.Find(id);
            gelenidbilgisininkodunubulmaseysi.adet = gelenidbilgisininkodunubulmaseysi.adet + 1;
            db.SaveChanges();
            return RedirectToAction("listele");
        }
        public ActionResult arttir(int id)
        {
            urun yeniurun = new urun();
            var gelenidbilgisininkodunubulmaseysi = db.urunler.Find(id);
            gelenidbilgisininkodunubulmaseysi.adet = gelenidbilgisininkodunubulmaseysi.adet - 1;
            db.SaveChanges();
            return RedirectToAction("listele");
        }
        public ActionResult adetekle(int id, int degis)
        {
            var gelenidbilgisininkodunubulmaseysi = db.urunler.Find(id);
            gelenidbilgisininkodunubulmaseysi.adet = degis;
            db.SaveChanges();

            return RedirectToAction("listele");
        }
    }
}

yeniProje/Views/urun/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

yeniProje/Views/urun/indirimyap.cshtml
@{
    ViewBag.Title = "indirimyap";
}

<h2>İndirim Yapımı</h2>

@using (Html.BeginForm("indirimyap", "urun", FormMethod.Post))
{
    <dl>
        <dt>İndirim Oranı (0-100 arası)</dt>
        <dd><input type="text" name="indirimorani" /></dd>

        <dt>İndirim Limiti</dt>
        <dd><input type="text" name="indirimlimiti" /></dd>

        <dt>Uygulamak için</dt>
        <dd><input type="submit" /></dd>
    </dl>
}

yeniProje/Views/urun/listele.cshtml
@model List<yeniProje.Models.urun>
@{
    ViewBag.Title = "listele";
}

<h2>Ürün Stok Listesi</h2>

<div class="container">
    <table class="table table-striped table-bordered" style="background-color:white;">
        <tr>
            <th>Ürün İsmi</th>
            <th>Ürün Fiyatı</th>
            <th>Ürün Adeti</th>
            <th>Ürün Açıklaması</th>
            <th>Kontrol Kısmı</th>
            <th>Kontrol Kısmı</th>
            <th>Stok Adedi Güncelleme</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>

                <td>@Html.DisplayFor(i => item.urunismi)</td>

                <td>@Html.DisplayFor(i => item.fiyati)</td>

                <td>@Html.DisplayFor(i => item.adet)</td>

                <td>@Html.DisplayFor(i => item.aciklama)</td>

                <td>@Html.ActionLink("Adeti Arttır", "azalt", new { id = item.id }, new { @class = "btn btn-success" })</td>

                <td>@Html.ActionLink("Adeti Azalt", "arttir", new { id = item.id }, new { @class = "btn btn-danger" })</td>

                <td>
                    @using (Html.BeginForm("adetekle", "urun", FormMethod.Post))
                    {
                        <input type="hidden" name="id" value="@item.id" />
                        <input type="text" name="degis" value="@item.adet" />
                        <input type="submit" value="degistir" />
                    }
                </td>

            </tr>
        }
    </table>
</div>

yeniProje/Views/urun/seçim.cshtml
@model yeniProje.Models.urun
    @{
        ViewBag.Title = "seçim";
    }

    <h2>seçim</h2>


    <td>@Html.ActionLink("Max Fiyatlı", "seçim", "urun", new { id = 1 },null)</td>&nbsp;&nbsp;&nbsp;
    <td>@Html.ActionLink("Min Fiyatlı", "seçim", "urun", new { id = 2 }, null)</td>&nbsp;&nbsp;&nbsp;
    <td>@Html.ActionLink("Stokta en yüksek", "seçim", "urun",  new { id = 3 }, null)</td>&nbsp;&nbsp;&nbsp;
    <br />
    <br />
             
           <dl>
               <dt>Ürün İsmi</dt>
               <dd>@Html.DisplayFor(i => i.urunismi)</dd>

               <dt>Ürün Fiyatı</dt>
               <dd>@Html.DisplayFor(i => i.fiyati)</dd>

               <dt>Ürün Adeti</dt>
               <dd>@Html.DisplayFor(i => i.adet)</dd>

               <dt>Ürün Açıklaması</dt>
               <dd>@Html.DisplayFor(i => i.aciklama)</dd>
           </dl>

yeniProje/Views/urun/urungir.cshtml
@model yeniProje.Models.urun
@{
    ViewBag.Title = "Ürün Girişi";
}

<h2>Ürün Girişi</h2>
<div style="color:green;"><h4>@ViewBag.mesaj</h4></div>

@using (Html.BeginForm("urungir", "urun"))
{
    <dl>
        <dt>Ürün Adı</dt>
        <dd>@Html.TextBoxFor(i => Model.urunismi)</dd>

        <dt>Ürün Fiyatı</dt>
        <dd>@Html.TextBoxFor(i => Model.fiyati)</dd>

        <dt>Ürün Adeti</dt>
        <dd>@Html.TextBoxFor(i => Model.adet)</dd>

        <dt>Ürün Açıklaması</dt>
        <dd>@Html.TextBoxFor(i => Model.aciklama)</dd>

        <dt> Kayıt Etme işlemi için :</dt>
        <dd><input type="submit" value="Kaydet" /></dd>
    </dl>
}

yeniProje/Views/urun/zam.cshtml
@model List<yeniProje.Models.urun>
@{
    ViewBag.Title = "zam";
}

<h2>Zam Oranı Girişi</h2>

@using (Html.BeginForm("zam", "urun", FormMethod.Post))
{
    <dl>
        <dt>Ürün Zam Oranı Giriniz(% cinsinden):</dt>
        <dt>(0 ila 100 arası veri girişi yapınız)</dt>
        <dd>
            <input type="text" name="zamorani" />
        </dd>
        <br />

        <dt>Uygulamak için:</dt>
        <dd><input type="submit" value="Uygula" /></dd>
    </dl>
}

<br />
<br />